SELECT HOURS.HOUR, NVL(COUNT, 0)
FROM ( SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24')) OUTS,
    (SELECT LEVEL-1 AS HOUR FROM DUAL 
    CONNECT BY LEVEL<=24) HOURS
WHERE HOURS.HOUR = OUTS.HOUR(+)
ORDER BY HOURS.HOUR;